LIBS = -lGL -lGLU -lglut -lm

ejemplo4: example4.c
	gcc -o $@ $< $(LIBS)

ejemplo3: example3.c
	gcc -o $@ $< $(LIBS)

ejercicio: ejercicio.c
	gcc -o $@ $< $(LIBS)

cube: cube.c
	gcc -o $@ $< $(LIBS)
	
